fileVersion: 1
id: "3"
mappingDefinitions:
  COALESCE_CDC:
    database: USER$ARSHADM
    schema: COALESCE_CDC
  COALESCE_INT:
    database: USER$ARSHADM
    schema: COALESCE_INT
  COALESCE_SRC:
    database: USER$ARSHADM
    schema: COALESCE_SRC
  COALESCE_TGT:
    database: USER$ARSHADM
    schema: COALESCE_TGT
name: PROD
type: Environment
